# Generated by Django 5.0.2 on 2024-02-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_urhajozas', '0002_becenev'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='becenev',
            options={'verbose_name': 'Becenev', 'verbose_name_plural': 'Becenevek'},
        ),
        migrations.AlterField(
            model_name='urhajos',
            name='urido',
            field=models.CharField(max_length=10),
        ),
    ]
