# Generated by Django 5.0.2 on 2024-02-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_urhajozas', '0003_alter_becenev_options_alter_urhajos_urido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kuldetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('megnevezes', models.CharField(max_length=256)),
                ('kezdet', models.DateField()),
                ('veg', models.DateField()),
                ('resztvevoi', models.ManyToManyField(to='app_urhajozas.urhajos')),
            ],
            options={
                'verbose_name': 'Küldetés',
                'verbose_name_plural': 'Küldetések',
            },
        ),
    ]
