# Generated by Django 5.0.2 on 2024-02-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_urhajozas', '0004_kuldetes'),
    ]

    operations = [
        migrations.AddField(
            model_name='kuldetes',
            name='az',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urhajos',
            name='az',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
